name: ADPTG

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        required: false
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Git Repository
      run: |
        git init
        git config user.name "SpoinkOSDevs"
        git config user.email "SpoinkOSGithub@gmail.com"

    - name: Setup Python and Git LFS
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Required Tools
      run: |
        echo "Installing essential tools..."
        sudo apt-get update -qq && sudo apt-get install -yqq git-lfs 
        git lfs install
        sudo apt-get install -yqq python3-pip speedtest-cli
        pip3 install --upgrade pip
        pip3 install speedtest-cli
  
    
  
    - name: Download Latest Release
      run: |
        echo "Downloading latest release..."
        wget -N --timestamping https://archive.org/download/spoink-os/SpoinkOS-Latest-desktop-amd64.iso -O latest.iso

    - name: Split ISO into 3 Chunks
      run: |
        split -b $(( $(stat --printf="%s" latest.iso) / 3 )) latest.iso latest_chunk

    - name: Configure Git LFS for ISO chunks
      run: |
        git config pull.rebase false
        git lfs track "*.iso*"
        git add .gitattributes latest_chunk*
        git commit -m "Use Git LFS for large ISO file chunks"
        git remote add origin https://SpoinkOSDevs:${{ secrets.GH_TOKEN }}@github.com/SpoinkOSDevs/SpoinkOS.git
        git pull origin master --allow-unrelated-histories --no-rebase

   
    - name: Release and tag
      uses: planet-code/release-tag-action@1.0.0
      id: create-release
      with:
      release-branch-pattern: # optional, default is release/
      show-changelog: # optional, default is true
    env:
     GITHUB_TOKEN: ${{ env.GH_TOKEN }}
  
      
    - name: Upload ISO Chunks to Release using Git LFS
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: latest_chunkaa
        asset_name: latest_chunkaa
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ env.GH_TOKEN }}

    - name: Upload more ISO Chunks if needed
      run: |
        for chunk in latest_chunkab latest_chunkac; do
          git lfs fetch
          git lfs push --all origin
          git lfs pull
          git lfs track "$chunk"
          git add "$chunk"
          git commit -m "Add $chunk"
          git push -u origin master
          git lfs push --all origin
          git lfs pull
          echo "::set-output name=asset_paths::${{ steps.upload-release-assets.outputs.asset_paths }},$chunk"
        done

  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Clean Up
      run: |
        echo "Cleaning up..."
        rm -f latest.iso latest_chunk*
