name: ADPTG

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        required: false
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Git Repository
      run: |
        git init
        git config user.name "SpoinkOSDevs"
        git config user.email "SpoinkOSGithub@gmail.com"

    - name: Setup Python and Git LFS
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Required Tools
      run: |
        echo "Installing essential tools..."
        sudo apt-get update -qq && sudo apt-get install -yqq git-lfs
        git lfs install

    - name: Download Latest Release
      run: |
        echo "Downloading latest release..."
        wget -N --timestamping https://archive.org/download/spoink-os/SpoinkOS-Latest-desktop-amd64.iso -O latest.iso

    - name: Configure Git LFS for ISO file
      run: |
        git lfs track "*.iso"
        git add .gitattributes
        git add latest.iso
        git commit -m "Use Git LFS for large ISO file"
        git remote add origin https://SpoinkOSDevs:${{ secrets.GH_TOKEN }}@github.com/SpoinkOSDevs/SpoinkOS.git
        git push -u origin master

    - name: Create GitHub Release
      id: create-release
      uses: actions/create-release@v1
      with:
        tag_name: Stable
        release_name: Latest Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ env.GH_TOKEN }}

    - name: Upload ISO to Release using Git LFS
      id: upload-release-asset
      run: |
        git lfs fetch
        git lfs push --all origin
      env:
        GITHUB_TOKEN: ${{ env.GH_TOKEN }}

  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Clean Up
      run: |
        echo "Cleaning up..."
        rm -f latest.iso
