name: ADPTG

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        required: false
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Required Tools
      run: |
        echo "Installing essential tools..."
        sudo apt-get update -qq && sudo apt-get install -yqq git-lfs

    - name: Download Latest Release
      run: |
        echo "Downloading latest release..."
        wget -N --timestamping https://archive.org/download/spoink-os/SpoinkOS-Latest-desktop-amd64.iso -O latest.iso

- name: Create GitHub Release
  id: create-release
  uses: actions/create-release@v1
  with:
    token: ${{ secrets.GH_TOKEN }}
    tag_name: v$(date +'%Y%m%d%H%M%S')
    release_name: Release $(date +'%Y%m%d%H%M%S')
    draft: false
    prerelease: false

- name: Upload ISO to Release
  id: upload-release-asset
  uses: actions/upload-release-asset@v1
  with:
    upload_url: ${{ steps.create-release.outputs.upload_url }}
    asset_path: ./latest.iso
    asset_name: latest.iso
    asset_content_type: application/octet-stream
    token: ${{ secrets.GH_TOKEN }}


  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Clean Up
      run: |
        echo "Cleaning up..."
        rm -f latest.iso
