name: ADPTG

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        required: false
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Git Repository
      run: |
        git init
        git config user.name "SpoinkOSDevs"
        git config user.email "SpoinkOSGithub@gmail.com"

    - name: Download Latest Release
      run: |
        echo "Downloading latest release..."
        wget -N --timestamping https://archive.org/download/spoink-os/*.iso -O latest.iso

    - name: Split ISO into 3 Chunks
      run: |
        split -b $(( $(stat --printf="%s" latest.iso) / 3 )) latest.iso latest_chunk

    - name: Configure Git LFS for ISO chunks
      run: |
        git lfs track "*.iso*"
        git add .gitattributes latest_chunk*
        git commit -m "Use Git LFS for large ISO file chunks"
        git remote add origin https://github.com/SpoinkOSDevs/SpoinkOS
        git pull origin master --allow-unrelated-histories
        git push -u origin master

    - name: Create GitHub Release
      id: create-release
      uses: actions/create-release@v1
      with:
        tag_name: v$(date +'%Y%m%d%H%M%S')-$(openssl rand -hex 4)  # Use a random string
        release_name: Release $(date +'%Y%m%d%H%M%S')
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ env.GH_TOKEN }}

    - name: Upload ISO Chunks to Release using Git LFS
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: latest_chunkaa
        asset_name: latest_chunkaa
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ env.GH_TOKEN }}

    - name: Upload more ISO Chunks if needed
      run: |
        for chunk in latest_chunkab latest_chunkac; do
          git lfs fetch
          git lfs push --all origin
          git lfs pull
          git lfs track "$chunk"
          git add "$chunk"
          git commit -m "Add $chunk"
          git push -u origin master
          git lfs push --all origin
          git lfs pull
          echo "::set-output name=asset_paths::${{ steps.upload-release-assets.outputs.asset_paths }},$chunk"
        done

  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Clean Up
      run: |
        echo "Cleaning up..."
        rm -f latest.iso latest_chunk*
