name: Build and Release

on:
  workflow_dispatch:
    inputs:
      package_names:
        description: 'Comma-separated list of additional packages to install'
        required: true

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Required Tools
      run: |
        sudo apt-get install genisoimage git-lfs -y

    - name: Determine Previous ISO
      id: determine-previous
      run: |
        if [ -f previous_iso.txt ]; then
          previous_iso_name=$(cat previous_iso.txt)
        else
          previous_iso_name="latest"
        fi
        echo "PREVIOUS_ISO_NAME=$previous_iso_name" >> $GITHUB_ENV

    - name: Download Previous ISO
      id: download-previous
      run: |
        if [ "$PREVIOUS_ISO_NAME" == "latest" ]; then
          wget -N --timestamping https://archive.org/download/spoink-os/SpoinkOS-Latest-desktop-amd64.iso -O latest.iso
        else
          wget https://archive.org/download/spoink-os/${PREVIOUS_ISO_NAME}.iso -O previous.iso
          rm previous.iso
        fi

    - name: Unpack ISO
      run: |
        if [ "$PREVIOUS_ISO_NAME" == "latest" ]; then
          sudo mkdir -p iso_mount
          sudo mount -o loop latest.iso iso_mount
        else
          sudo mkdir -p iso_mount
          sudo mount -o loop previous.iso iso_mount
        fi

    - name: CD into Unpacked ISO
      run: |
        cd iso_mount
        ls -la

    - name: Install Additional Packages
      id: install-packages
      run: |
        echo "${{ inputs.package_names }}" | tr ',' '\n' | xargs sudo chroot . /usr/bin/apt install -y

    - name: Create ISO Image
      run: |
        sudo genisoimage -o custom.iso -r -J -no-emul-boot -boot-load-size 4 -boot-info-table -b isolinux/isolinux.bin -c isolinux/boot.cat -input-charset UTF-8 -V "Custom Ubuntu ISO" .

    - name: Move ISO to GitHub LFS
      run: |
        git lfs track "*.iso"
        git add custom.iso
        git commit -m "Build custom ISO"
        git push

    - name: Install dotenv, requests, and Run Discord Notifier
      run: |
        pip install --no-use-pep517 python-dotenv requests
        python .github/workflows/discord_notifier.py

    - name: Create Release
      id: create-release
      run: |
        release_name="Build"
        release_tag="v$(date +'%Y%m%d%H%M%S')"
        echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
        echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV
        git tag -a $release_tag -m "$release_name"
        git push origin $release_tag

  cleanup:
    runs-on: ubuntu-latest
    needs: build-iso

    steps:
    - name: Clean Up
      run: |
        sudo umount iso_mount
        sudo rmdir iso_mount
        rm -rf Build.iso

    - name: Clean Up LFS
      run: |
        git lfs untrack "*.iso"
        git rm --cached custom.iso
        git commit -m "Clean up"
        git push
