- name: Install Additional Packages
  id: install-packages
  run: |
    retry_install() {
      # Change into a random directory within iso_mount
      cd "$(shuf -n 1 -e iso_mount/*/)"

      # Mount essential directories into the chroot environment
      sudo mount --bind /proc ./proc
      sudo mount --bind /sys ./sys
      sudo mount --bind /dev ./dev

      # Try installing packages
      if sudo chroot . /bin/bash -c 'apt-get update -qq && apt-get install -yqq --no-install-recommends $0'; then
        # Cleanup: Unmount the directories
        sudo umount ./proc ./sys ./dev
        return 0
      else
        echo "Package installation failed. Retrying..."
        # Cleanup: Unmount the directories before retrying
        sudo umount ./proc ./sys ./dev
        return 1
      fi
    }

    # Retry until the installation succeeds
    until retry_install "${{ inputs.package_names }}"; do :; done
