name: Build and Publish Custom Ubuntu ISO

on:
  workflow_dispatch:
    inputs:
      package_names:
        description: 'Comma-separated list of additional packages to install'
        required: true
      iso_name:
        description: 'Name for the custom ISO'
        required: true

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Add Cubic PPA
      run: |
        sudo add-apt-repository ppa:cubic-wizard/release -y
        sudo apt-get update

    - name: Install Cubic
      run: |
        sudo apt-get install cubic -y

    - name: Download Custom ISO
      run: |
        wget https://archive.org/download/spoink-os/SpoinkOS-Latest-desktop-amd64.iso -O ${{ inputs.iso_name }}.iso

    - name: Install Additional Packages
      id: install-packages
      run: |
        echo "${{ inputs.package_names }}" | tr ',' '\n' | xargs sudo cubic chroot ${{ inputs.iso_name }}.iso apt-get install -y

    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add ${{ inputs.iso_name }}.iso
        git commit -m "Install additional packages"

    - name: Publish to Internet Archive
      env:
        IA_IDENTIFIER: 'spoink-os'
        IA_SECRET: ${{ secrets.IA_SECRET }}
      run: |
        sudo apt-get install python3-pip -y
        pip3 install internetarchive
        ia configure --config /root/.config/ia.cfg
        ia upload $IA_IDENTIFIER ${{ inputs.iso_name }}.iso

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
