name: Discord Notification

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  send-discord-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py python-dotenv requests

    - name: Run Python Script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python .github/scripts/discord_notification.py  # Adjust the path accordingly
